### PR TITLE
Try to avoid messing with Mason's `compile` interface

### PR DESCRIPTION
**Pull request by brenhinkeller**
This makes more of the tests pass -- should be fine re: Mason's interface now AFAICT.

Now it seems there's just an issue where something added here is causing some dynamic dispatch (`_ijl_apply_generic `) and some allocations (`_gpu_gc_pool_alloc`) that didn't used to be there in the integration tests when we go to actually compile things

### CODE REVIEW

**Comment by brenhinkeller** [comment]
Ok, I think most of the errors in CI now are not the fault of this PR.. If you want to go ahead and merge this we can figure out what to do in the main PR now

**Comment by giordano** [comment]
CC @gbaraldi (since he's not watching the repository)

**Comment by gbaraldi** [comment]
I wasn't really following what was going on. @brenhinkeller so I merge this and open a PR to upstream?

**Comment by brenhinkeller** [comment]
Yeah, exactly

**Comment by gbaraldi** [comment]
Ok, I broke the entire merging :smile:. I will do a manual merge and open a PR.

**Comment by brenhinkeller** [comment]
Huh yeah I'm not sure what happened.. may be related to my attempt at resolving conflicts before which apparently had some weird side affects

**Pull request merged**
